# -*- coding: utf-8 -*-
"""[Notebook] Python para Dados - Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1is4LcWdTE8uNjWMwh73SedkdXwwr7D8W
"""

import pandas as pd

"""# Dataframe e ordenação

**Utilizando o arquivo: carros.csv**

1. Faça o upload do CSV carros.csv
2. Print seu head com 10 linhas
3. Agora print as colunas e index do dataframe
4. Faça um sort decrescente no dataframe pelo estado com maior quantidade de carros
5. Descubra qual a proporção de carro para a população de cada estado e insira em uma nova coluna
6. Faça um dataframe com Estado e proporção de carro por habitante
"""



"""# Agregação de dados

**Utilizando o arquivos: concurso.csv**
7. Qual a média de idade por região?
8. Qual é a porcentagem de pessoas com deficiência?
9. Quantas pessoas são do estado do Piauí?

"""



"""# Indexação e fatiamento

**Utilizando o arquivos: concurso.csv**

Temos como base inscrições em um concurso público, utilizando indexação retorne:
10. Quantas pessoas são do estado do Piauí?
11. Quantas do ES são so sexo feminino?
12. Quantas pessoas nasceram antes de 1995?

13. Retorne os dados dos incritos com as colunas: nº inscrição, nome e idade.


"""



"""# Valores faltosos

14. Para os valores faltosos coloque:
- Se string: Falta informação
- Se número: mediana
15. Plote a porcentagem de dados faltosos para cada coluna.
"""

